### ISSUE TITLE
Trouble while using my GitArtwork action

### ISSUE THREAD

**Issue by jasineri** [TechDreams-Innovations/Logo#2]
Hello there!

I noticed that you encountered some trouble while using my GitArtwork action on your GitHub repository. I'm here to help!

To resolve the issue you experienced, I recommend checking your repository's Actions settings. Follow these steps:

    1. Visit your repository's page on GitHub.
    2. Click on the "Settings" tab located at the top-right corner.
    3. On the left-hand sidebar, select "Actions".
    4. In the "General" section, under "Workflow permissions" double-check that the "Read and write permissions" option is enabled.

By ensuring that the "Read and write permissions" are set in the "Workflow permissions" section, you should be able to overcome the problem you faced.

If you have any further questions or need additional assistance, feel free to reach out. Enjoy using GitArtwork and have fun with your GitHub projects!

Best regards,
jasineri

**Comment by CodeMaster7000** [comment]
@jasineri I am so sorry that I did not read your comment in time, but thank you so much!

However, the option is greyed out - is there any way I can fix this?

![Screenshot 2023-08-11 133652](https://github.com/TechDreams-Innovations/Logo/assets/95772109/e4698d77-daef-4b44-985d-bafaefc1ae21)
